name: 'Hello World'
description: 'Greet someone'
inputs:
  image:
    description:
    default: ghcr.io/${{ github.repository }}
  tag:  
    description: 'Image tag'
    default: ${{ github.event.release.tag_name }}
  registry:
    description: 'Container registry'
    default: ghcr.io
  username:
    description: 'Container registry username'
    required: true
  password:
    description: 'Container registry password'
    required: true
  platforms: 
    descriptions: 'Platforms to build for'
    default: 'linux/amd64'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/example.sh
      shell: bash
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ inputs.image }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        platforms: ${{ inputs.platforms }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}